# Generated by Django 3.1.3 on 2020-11-27 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_member'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 7, 58, 26, 482971, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
