# Generated by Django 3.1.3 on 2020-11-27 08:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20201127_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 8, 10, 34, 382462, tzinfo=utc)),
        ),
    ]
