# Generated by Django 3.1.3 on 2020-12-02 09:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20201128_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 9, 26, 35, 209513, tzinfo=utc)),
        ),
    ]
