# Generated by Django 3.1.3 on 2020-12-02 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20201202_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 9, 28, 47, 650103, tzinfo=utc)),
        ),
    ]
